exclude_paths:
  - 'core/src/index/thirdparty/**'
  - 'sdk/build-support/**'
  - 'sdk/thirdparty/**'
  - 'core/build-support/**'
  - 'core/src/grpc/gen-milvus/**'
  - 'core/src/grpc/gen-status/**'
  - 'sdk/grpc-gen/**'
  - 'core/thirdparty/**'
  - 'ci/**'
  - 'docker/**'
  - 'docs/**'
  - 'tests/**'
  - '.github/**'
  - '.jenkins/**'
