language: cpp
sudo: required
dist: bionic
addons:
  apt:
    update: true
before_install:
  - wget -qO- "https://cmake.org/files/v3.14/cmake-3.14.3-Linux-x86_64.tar.gz" | sudo tar --strip-components=1 -xz -C /usr/local
install:
  - source $TRAVIS_BUILD_DIR/ci/travis/install_dependency.sh
script:
  - $TRAVIS_BUILD_DIR/ci/travis/travis_build.sh
