language: cpp
sudo: required
dist: bionic

cache:
  directories:
    - $HOME/.ccache

addons:
  apt:
    update: true

before_install:
  - source ci/travis/before-install.sh

install:
  - source $TRAVIS_BUILD_DIR/ci/travis/install_dependency.sh

script:
  - sudo $TRAVIS_BUILD_DIR/ci/travis/travis_build.sh
