language: cpp
sudo: required
dist: bionic
addons:
  apt:
    update: true
install:
  - source $TRAVIS_BUILD_DIR/ci/travis/install_dependency.sh
script:
  - $TRAVIS_BUILD_DIR/ci/travis/travis_build.sh
