server_config:
  address: 0.0.0.0
  port: 19530                 # the port milvus listen to, default: 19530, range: 1025 ~ 65534
  gpu_index: 0                # the gpu milvus use, default: 0, range: 0 ~ gpu number - 1
  mode: single                # milvus deployment type: single, cluster

db_config:
  db_path: /tmp/milvus
  #URI format: dialect://username:password@host:port/database
  #All parts except dialect are optional, but you MUST include the delimiters
  db_backend_url: mysql://root:1234@:/test
  index_building_threshold: 1024          #build index file when raw data file size larger than this value, unit: MB

metric_config:
  is_startup: true      # if monitoring start: on, off
  collector: prometheus # metrics collector: prometheus
  prometheus_config:    # following are prometheus configure
    collect_type: pull  # prometheus collect data method
    port: 8080          # the port prometheus use to fetch metrics
    push_gateway_ip_address: 127.0.0.1 # push method configure: push gateway ip address
    push_gateway_port: 9091            # push method configure: push gateway port

license_config:         # license configure
  license_path: "/tmp/system.license" # license file path

cache_config:           # cache configure
  cpu_cache_capacity: 16   # how many memory are used as cache, unit: GB, range: 0 ~ less than total memory