server_config:
  address: 0.0.0.0
  port: 19530
  transfer_protocol: binary   #optional: binary, compact, json
  server_mode: thread_pool    #optional: simple, thread_pool
  gpu_index: 0                #which gpu to be used
  mode: single                #optional: single, cluster

db_config:
  db_path: /tmp/milvus
  #URI format: dialect://username:password@host:port/database
  #All parts except dialect are optional, but you MUST include the delimiters
  db_backend_url: sqlite://:@:/
  index_building_threshold: 1024          #build index file when raw data file size larger than this value, unit: MB

metric_config:
  is_startup: true # true is on, false is off
  collector: prometheus # prometheus, now we only have prometheus
  prometheus_config:
    collect_type: pull # pull means prometheus pull the message from server, push means server push metric to push gateway
    port: 8080
    push_gateway_ip_address: 127.0.0.1
    push_gateway_port: 9091

license_config:
  license_path: "/tmp/system.license"

cache_config:
    cpu_cache_capacity: 16   # memory pool to hold index data, unit: GB