server_config:
  address: 0.0.0.0
  port: 33001
  transfer_protocol: binary   #optional: binary, compact, json
  server_mode: thread_pool    #optional: simple, thread_pool
  gpu_index: 0                #which gpu to be used

db_config:
  db_path: /tmp/vecwise
  db_backend_url: http://127.0.0.1
  db_flush_interval: 5              #unit: second
  idmapper_max_open_file: 128

license_config:
  license_path: "/tmp/system.license"

cache_config:
    cpu_cache_capacity: 16   # unit: GB
    gpu_cache_capacity:  2   # unit: GB