version: '2.3'

networks:
    monitor:
        driver: bridge

services:
    prometheus:
        image: prom/prometheus:v2.11.1
        container_name: prometheus
        hostname: prometheus
        restart: always
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
            - ./server_down.yml:/etc/prometheus/node_down.yml
        ports:
            - "9090:9090"
        networks:
            - monitor

    alertmanager:
        image: prom/alertmanager
        container_name: alertmanager
        hostname: alertmanager
        restart: always
        volumes:
            - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
        ports:
            - "9093:9093"
        networks:
            - monitor

    grafana:
        image: grafana/grafana
        container_name: grafana
        hostname: grafana
        restart: always
        ports:
            - "3000:3000"
        networks:
            - monitor

    milvus:
        runtime: nvidia
        image: registry.zilliz.com/milvus/engine:branch-0.4.0-release
        container_name: milvus
        hostname: milvus
        restart: always
        volumes:
            - ../cpp/conf/server_config.yaml:/opt/milvus/cpp/conf/server_config.yaml
            - ../cpp/conf/log_config.conf:/opt/milvus/cpp/conf/log_config.conf
        ports:
            - "8080:8080"
            - "19530:19530"
        networks:
            - monitor
