apiVersion: v1
kind: Pod
metadata:
  name: milvus-build-env
  labels:
    app: milvus
    componet: build-env
spec:
  containers:
  - name: milvus-build-env
    image: registry.zilliz.com/milvus/milvus-build-env:v0.5.0
    command:
    - cat
    tty: true
    resources:
      limits:
        memory: "32Gi"
        cpu: "8.0"
        nvidia.com/gpu: 1
      requests:
        memory: "16Gi"
        cpu: "4.0"
