apiVersion: v1
kind: Pod
metadata:
  name: milvus-cpu-build-env
  labels:
    app: milvus
    componet: cpu-build-env
spec:
  containers:
  - name: milvus-cpu-build-env
    image: registry.zilliz.com/milvus/milvus-cpu-build-env:v0.6.0-ubuntu18.04
    env:
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: BUILD_ENV_IMAGE_ID
      value: "23476391bec80c64f10d44a6370c73c71f011a6b95114b10ff82a60e771e11c7"
    command:
    - cat
    tty: true
    resources:
      limits:
        memory: "32Gi"
        cpu: "8.0"
      requests:
        memory: "16Gi"
        cpu: "4.0"
  - name: milvus-mysql
    image: mysql:5.6
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: 123456
    ports:
    - containerPort: 3306
      name: mysql
