apiVersion: v1
kind: Pod
metadata:
  name: milvus-gpu-build-env
  labels:
    app: milvus
    componet: gpu-build-env
spec:
  containers:
  - name: milvus-gpu-build-env
    image: registry.zilliz.com/milvus/milvus-gpu-build-env:v0.7.0-centos7
    env:
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: OS_NAME
      value: "centos7"
    - name: BUILD_ENV_IMAGE_ID
      value: "a5ec9914737ea4727d88ae36b4a73ca5d817f19438ba913cc1de6a1ee2ed2336"
    command:
    - cat
    tty: true
    resources:
      limits:
        memory: "12Gi"
        cpu: "8.0"
        nvidia.com/gpu: 1
      requests:
        memory: "8Gi"
        cpu: "4.0"
  - name: milvus-mysql
    image: mysql:5.6
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: 123456
    ports:
    - containerPort: 3306
      name: mysql
