apiVersion: v1
kind: Pod
metadata:
  labels:
    app: milvus
    componet: build-env
spec:
  containers:
  - name: milvus-build-env
    image: registry.zilliz.com/milvus/milvus-build-env:v0.9
    command:
    - cat
    tty: true
