kind: Service
apiVersion: v1
metadata:
  name: milvus-ro-servers
  namespace: milvus
spec:
  type: ClusterIP
  selector:
    app: milvus
    tier: ro-servers
  ports:
  - protocol: TCP
    port: 19530
    targetPort: 19530

---

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: milvus-ro-servers
  namespace: milvus
spec:
  serviceName: "milvus-ro-servers"
  replicas: 1
  template:
    metadata:
      labels:
        app: milvus
        tier: ro-servers
    spec:
      terminationGracePeriodSeconds: 11
      containers:
      - name: milvus-ro-server
        image: milvusdb/milvus:0.5.0-d102119-ede20b
        imagePullPolicy: Always
        ports:
          - containerPort: 19530
        resources:
          limits:
            memory: "16Gi"
            cpu: "8.0"
          requests:
            memory: "14Gi"
        volumeMounts:
        - name: milvus-db-disk
          mountPath: /var/milvus
          subPath: dbdata
        - name: milvus-roserver-configmap
          mountPath: /opt/milvus/conf/server_config.yaml
          subPath: config.yml
        - name: milvus-roserver-configmap
          mountPath: /opt/milvus/conf/log_config.conf
          subPath: log.conf
      # imagePullSecrets:
      #   - name: regcred
      # tolerations:
      #   - key: "worker"
      #     operator: "Equal"
      #     value: "performance"
      #     effect: "NoSchedule"
      volumes:
      - name: milvus-roserver-configmap
        configMap:
            name: milvus-roserver-configmap
      - name: milvus-db-disk
        persistentVolumeClaim:
            claimName: milvus-db-disk
